---
#
# Main tasks, having all sub tasks to be included.
#

- include: hostname.yml
  when: enable_hostname

- include: swap.yml
  when: enable_swapfile

- include: packages.yml
  when: enable_packages

- include: users.yml
  when: enable_users

- include: kernel.yml
  when: enable_kernel

- include: git.yml
  when: enable_git

- include: ssh.yml
  when: enable_ssh

- include: miscellaneous.yml
  when: enable_misc
