---
- name: Check if swapfile exists
  stat:
    path={{ swap_path }}
    get_checksum=False
    get_md5=False
  register: swapfile

- name: Create swap file
  command: fallocate -l {{ swap_size }} {{ swap_path }}
  when: swapfile.stat.exists == False

- name: Make swap file
  command: mkswap {{ swap_path }}
  when: swapfile.stat.exists == False

- name: Make sure swapfile is included in /etc/fstab
  mount:
    name=swap
    src={{ swap_path }}
    fstype=swap
    state=present

- name: Enable swap file
  command: swapon -a
