---
- name: Check if swapfile exists
  stat:
    path={{ swap_path }}
    get_checksum=False
    get_md5=False
  register: swapfile

- name: Create swap file
  command: dd if=/dev/zero of={{ swap_path }} count={{ swap_size }} bs=1MiB
  when: swapfile.stat.exists == False

- name: Lock down swap file permission
  file:
    path: "{{ swap_path }}"
    owner: root
    group: root
    mode: 0600

- name: Make swap file
  command: mkswap {{ swap_path }}
  when: swapfile.stat.exists == False

- name: Make sure swapfile is included in /etc/fstab
  mount:
    name=swap
    src={{ swap_path }}
    fstype=swap
    state=present

- name: Enable swap file
  command: swapon -a
