---
- name: restart ssh
  debug: msg="checking config first"
  changed_when: True
  notify:
    - check ssh configuration
    - restart ssh - after config check

- name: check ssh configuration
  shell: /usr/sbin/sshd -t
  register: result
  changed_when: "result.rc != 0"
  check_mode: no # https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html

- name: restart ssh - after config check
  service:
    name={{ ssh_service }}
    state=restarted
